### ISSUE TITLE
Tôi không thể tìm thấy giao diện bán hàng của cửa hàng.

### ISSUE THREAD

**Issue by twirke** [4xmen/xshop#43]
Tôi muốn hỏi là nó chỉ cho phép có phần quản lý trong dự án này mà không có giao diện cửa hàng hay sao?

**Comment by A1Gard** [comment]
Hello bro, plz write english, Version 2 under construction, You can use v1 right now:

https://github.com/A1Gard/xshop.v1

Or otherwise you can design you front store ( `dashboard`, `theme`, `gfx ` or `area design`.

![image](https://github.com/user-attachments/assets/15630c1e-7d74-4988-a271-005ca891a096)
